### ISSUE TITLE
Permission problems in rootless Docker

### ISSUE THREAD

**Issue by notalexnot** [dokuwiki/docker#6] opened 2024-06-01 17:52 UTC
Hey!

I've been trying to setup DokuWiki correctly using rootless Docker, but I've found some problems:

 1. Using `user: "1000:1000"` gives me a "Permission denied" error while trying to create subfolders in the `storage` folder (even though it can create `storage` correctly).
 2. Not using `user: "1000:1000"` can create all the folders correctly, but for some reason it can't find them, saying: "The datadir ('pages') at /storage/data/pages is not found, isn't accessible or writable", even if I already ran the `install.php` file.

I don't know if it's relevant, but the `install.php` and other files in `/var/www/html` have owner 1001 and group 127. Thanks in advance, and sorry if this isn't something that can be fixed.

**Comment by splitbrain** [comment] 2024-06-02 12:02
I am not sure I am following you correctly.

As far as I know, rootless docker refers to the docker daemon running as unprivileged user. I don't have experience with that but I would assume that you need to run the dokuwiki container with the same UID that started the Docker daemon.

You do not specify it but it seems you are starting the container using docker compose. Are you using a bind mount or  a volume?

I noticed the following problem when using a volume:

* volumes are created by the docker daemon and thus are owned by root
* when the container is run with a given user, all processes within (including apache and our entrypoint) are run as that user and it will fail to write to the volume
* when the container is run as root, the volume will be populated correctly (by our entrypoint) but Apache drops the root privileges to the internal uid 33 and fails to write to the volume

I see two ways to fix this:

1) we somehow tell apache not to drop privileges and run as root
2) in our entry point we detect when we are running as root and change permissions to www-data (33) for all storage data

I think I prefer 2. @kossmac do you know how this is usually handled?

**Comment by splitbrain** [comment] 2024-06-02 14:30
The problems with volumes and running the container as root should have been addressed by the above commit. I'm closing this, feel free to reopen with new info if your specific problem is not addressed.

**Closed by splitbrain** 2024-06-02 14:30 UTC

**Comment by notalexnot** [comment] 2024-06-02 16:46
Thanks! That actually solved it. I was using a bind mount as the compose file in the repo, it now works fine :D

**Comment by leonardus** [comment] 2024-11-13 21:53
> The problems with volumes and running the container as root should have been addressed by the above commit. I'm closing this, feel free to reopen with new info if your specific problem is not addressed.

Hello, although the entrypoint script changes the permissions on `/storage` to `www-data`, the extensions contained in `/storage/lib/plugins` are symlinks to files in `/var/www/html`, which is a directory owned by root, and as such, the web interface shows permissions errors for extensions.
I will admit that I'm not an expert with this software, so I'm not sure if this is by design, or a configuration error on my own part.
